export const REGISTER_PATHNAME: string = '/sign-up'
export const LOGIN_PATHNAME: string = '/sign-in'
export const MAIN_PATHNAME: string = '/'
export const UKNOWN_PATHNAME: string = '*'
export const GAME_HISTORY_PATHNAME: string = '/game-history'
export const GAME_RULES_PATHNAME: string = '/rules'
