type Pathname = '/sign-up' | '/sign-in' | '/' | '*' | '/game-history' | '/rules' | '/nfl-history' | '/league-structure' | '/season-structure' | '/draft'
| '/cardinals' | '/falcons' | '/ravens' | '/bills' | '/panthers' | '/bears' | '/bengals' | '/browns' | '/cowboys' | '/broncos'
| '/lions' | '/packers' | '/texans' | '/colts' | '/jaguars' | '/chiefs' | '/raiders' | '/chargers' | '/rams' | '/dolphins'
| '/vikings' | '/patriots' | '/saints' | '/giants' | '/jets' | '/eagles' | '/steelers' | '/49ers' | '/seahawks'
| '/buccaneers' | '/titans' | '/commanders'| '/what-is-superbowl' | '/superbowl-champions'

export const REGISTER_PATHNAME: Pathname = '/sign-up'
export const LOGIN_PATHNAME: Pathname = '/sign-in'
export const MAIN_PATHNAME: Pathname = '/'
export const UKNOWN_PATHNAME: Pathname = '*'
export const GAME_HISTORY_PATHNAME: Pathname = '/game-history'
export const GAME_RULES_PATHNAME: Pathname = '/rules'
export const NFL_HISTORY_PATHNAME: Pathname = '/nfl-history'
export const LEAGUE_STRUCTURE_PATHNAME: Pathname = '/league-structure'
export const SEASON_STRUCTURE_PATHNAME: Pathname = '/season-structure'
export const DRAFT_PATHNAME: Pathname = '/draft'
export const ARIZONA_CARDINALS_PATHNAME: Pathname = '/cardinals'
export const ATLANTA_FALCONS_PATHNAME: Pathname = '/falcons'
export const BALTIMORE_RAVENS_PATHNAME: Pathname = '/ravens'
export const BUFFALO_BILLS_PATHNAME: Pathname = '/bills'
export const CAROLINA_PANTHERS_PATHNAME: Pathname = '/panthers'
export const CHICAGO_BEARS_PATHNAME: Pathname = '/bears'
export const CINCINNATI_BENGALS_PATHNAME: Pathname = '/bengals'
export const CLEVELAND_BROWNS_PATHNAME: Pathname = '/browns'
export const DALLAS_COWBOYS_PATHNAME: Pathname = '/cowboys'
export const DENVER_BRONCOS_PATHNAME: Pathname = '/broncos'
export const DETROIT_LIONS_PATHNAME: Pathname = '/lions'
export const GREEN_BAY_PACKERS_PATHNAME: Pathname = '/packers'
export const HOUSTON_TEXANS_PATHNAME: Pathname = '/texans'
export const INDIANAPOLIS_COLTS_PATHNAME: Pathname = '/colts'
export const JACKSONVILLE_JAGUARS_PATHNAME: Pathname = '/jaguars'
export const KANSAS_CITY_CHIEFS_PATHNAME: Pathname = '/chiefs'
export const LAS_VEGAS_RAIDERS_PATHNAME: Pathname = '/raiders'
export const LOS_ANGELES_CHARGERS_PATHNAME: Pathname = '/chargers'
export const LOS_ANGELES_RAM_PATHNAME: Pathname = '/rams'
export const MIAMI_DOLPHINS_PATHNAME: Pathname = '/dolphins'
export const MINNESOTA_VIKINGS_PATHNAME: Pathname = '/vikings'
export const NEW_ENGLAND_PATRIOTS_PATHNAME: Pathname = '/patriots'
export const NEW_ORLEANS_SAINTS_PATHNAME: Pathname = '/saints'
export const NEW_YORK_GIANTS_PATHNAME: Pathname = '/giants'
export const NEW_YORK_JETS_PATHNAME: Pathname = '/jets'
export const PHILADELPHIA_EAGLES_PATHNAME: Pathname = '/eagles'
export const PITTSBURGH_STEELERS_PATHNAME: Pathname = '/steelers'
export const SAN_FRANCISCO_49ERS_PATHNAME: Pathname = '/49ers'
export const SEATTLE_SEAHAWKS_PATHNAME: Pathname = '/seahawks'
export const TAMPA_BAY_BUCCANEERS_PATHNAME: Pathname = '/buccaneers'
export const TENNESSEE_TITANS_PATHNAME: Pathname = '/titans'
export const WASHINGTON_COMMANDERS_PATHNAME: Pathname = '/commanders'
export const SUPERBOWL_WHAT_IS_PATHNAME: Pathname = '/what-is-superbowl'
export const SUPERBOWL_CHAMPIONS_PATHNAME: Pathname = '/superbowl-champions'
