import {
  GAME_HISTORY_PATHNAME,
  GAME_RULES_PATHNAME,
  NFL_HISTORY_PATHNAME,
  LEAGUE_STRUCTURE_PATHNAME,
  SEASON_STRUCTURE_PATHNAME,
  DRAFT_PATHNAME,
  ARIZONA_CARDINALS_PATHNAME,
  ATLANTA_FALCONS_PATHNAME,
  BALTIMORE_RAVENS_PATHNAME,
  BUFFALO_BILLS_PATHNAME,
  CAROLINA_PANTHERS_PATHNAME,
  CHICAGO_BEARS_PATHNAME,
  CINCINNATI_BENGALS_PATHNAME,
  CLEVELAND_BROWNS_PATHNAME,
  DALLAS_COWBOYS_PATHNAME,
  DENVER_BRONCOS_PATHNAME,
  DETROIT_LIONS_PATHNAME,
  GREEN_BAY_PACKERS_PATHNAME,
  HOUSTON_TEXANS_PATHNAME,
  INDIANAPOLIS_COLTS_PATHNAME,
  JACKSONVILLE_JAGUARS_PATHNAME,
  KANSAS_CITY_CHIEFS_PATHNAME,
  LAS_VEGAS_RAIDERS_PATHNAME,
  LOS_ANGELES_CHARGERS_PATHNAME,
  LOS_ANGELES_RAM_PATHNAME,
  MIAMI_DOLPHINS_PATHNAME,
  MINNESOTA_VIKINGS_PATHNAME,
  NEW_ENGLAND_PATRIOTS_PATHNAME,
  NEW_ORLEANS_SAINTS_PATHNAME,
  NEW_YORK_GIANTS_PATHNAME,
  NEW_YORK_JETS_PATHNAME,
  PHILADELPHIA_EAGLES_PATHNAME,
  PITTSBURGH_STEELERS_PATHNAME,
  SAN_FRANCISCO_49ERS_PATHNAME,
  SEATTLE_SEAHAWKS_PATHNAME,
  TAMPA_BAY_BUCCANEERS_PATHNAME,
  TENNESSEE_TITANS_PATHNAME,
  WASHINGTON_COMMANDERS_PATHNAME,
  SUPERBOWL_WHAT_IS_PATHNAME,
  SUPERBOWL_CHAMPIONS_PATHNAME
} from './pathName.ts'

import {
  GAME_HISTORY_LABEL,
  GAME_RULES_LABEL,
  NFL_HISTORY_LABEL,
  LEAGUE_STRUCTURE_LABEL,
  SEASON_STRUCTURE_LABEL,
  DRAFT_LABEL,
  SUPERBOWL_WHAT_IS_LABEL,
  SUPERBOWL_CHAMPIONS_LABEL,
  ARIZONA_CARDINALS_LABEL,
  ATLANTA_FALCONS_LABEL,
  BALTIMORE_RAVENS_LABEL,
  BUFFALO_BILLS_LABEL,
  CAROLINA_PANTHERS_LABEL,
  CHICAGO_BEARS_LABEL,
  CINCINNATI_BENGALS_LABEL,
  CLEVELAND_BROWNS_LABEL,
  DALLAS_COWBOYS_LABEL,
  DENVER_BRONCOS_LABEL,
  DETROIT_LIONS_LABEL,
  GREEN_BAY_PACKERS_LABEL,
  HOUSTON_TEXANS_LABEL,
  INDIANAPOLIS_COLTS_LABEL,
  JACKSONVILLE_JAGUARS_LABEL,
  KANSAS_CITY_CHIEFS_LABEL,
  LAS_VEGAS_RAIDERS_LABEL,
  LOS_ANGELES_CHARGERS_LABEL,
  LOS_ANGELES_RAM_LABEL,
  MIAMI_DOLPHINS_LABEL,
  MINNESOTA_VIKINGS_LABEL,
  NEW_ENGLAND_PATRIOTS_LABEL,
  NEW_ORLEANS_SAINTS_LABEL,
  NEW_YORK_GIANTS_LABEL,
  NEW_YORK_JETS_LABEL,
  PHILADELPHIA_EAGLES_LABEL,
  PITTSBURGH_STEELERS_LABEL,
  SAN_FRANCISCO_49ERS_LABEL,
  SEATTLE_SEAHAWKS_LABEL,
  TAMPA_BAY_BUCCANEERS_LABEL,
  TENNESSEE_TITANS_LABEL,
  WASHINGTON_COMMANDERS_LABEL
} from './teamLabels.ts'

import {
  cardinalsLogo,
  falconsLogo,
  ravensLogo,
  billsLogo,
  panthersLogo,
  bearsLogo,
  bengalsLogo,
  brownsLogo,
  cowboysLogo,
  broncosLogo,
  lionsLogo,
  packersLogo,
  texansLogo,
  coltsLogo,
  jaguarsLogo,
  chiefsLogo,
  raidersLogo,
  chargersLogo,
  ramsLogo,
  dolphinsLogo,
  vikingsLogo,
  patriotsLogo,
  saintsLogo,
  giantsLogo,
  jetsLogo,
  eaglesLogo,
  steelersLogo,
  ersLogo,
  seahawksLogo,
  buccaneersLogo,
  titansLogo,
  commandersLogo
} from './teamsLogos.ts'

import MenuItem from "../interfaces/MenuItem.ts"

const GAME_HISTORY: MenuItem = {
  label: GAME_HISTORY_LABEL,
  link: GAME_HISTORY_PATHNAME
}

const GAME_RULES: MenuItem = {
  label: GAME_RULES_LABEL,
  link: GAME_RULES_PATHNAME
}

const NFL_HISTORY: MenuItem = {
  label: NFL_HISTORY_LABEL,
  link: NFL_HISTORY_PATHNAME
}

const LEAGUE_STRUCTURE: MenuItem = {
  label: LEAGUE_STRUCTURE_LABEL,
  link: LEAGUE_STRUCTURE_PATHNAME
}

const SEASON_STRUCTURE: MenuItem = {
  label: SEASON_STRUCTURE_LABEL,
  link: SEASON_STRUCTURE_PATHNAME
}

const DRAFT: MenuItem = {
  label: DRAFT_LABEL,
  link: DRAFT_PATHNAME
}

const SUPERBOWL_WHAT_IS: MenuItem = {
  label: SUPERBOWL_WHAT_IS_LABEL,
  link: SUPERBOWL_WHAT_IS_PATHNAME
}

const SUPERBOWL_CHAMPIONS: MenuItem = {
  label: SUPERBOWL_CHAMPIONS_LABEL,
  link: SUPERBOWL_CHAMPIONS_PATHNAME
}

const ARIZONA_CARDINALS_TEAM: MenuItem = {
  label: ARIZONA_CARDINALS_LABEL,
  link: ARIZONA_CARDINALS_PATHNAME,
  logo: cardinalsLogo
}

const ATLANTA_FALCONS_TEAM: MenuItem = {
  label: ATLANTA_FALCONS_LABEL,
  link: ATLANTA_FALCONS_PATHNAME,
  logo: falconsLogo
}

const BALTIMORE_RAVENS_TEAM: MenuItem = {
  label: BALTIMORE_RAVENS_LABEL,
  link: BALTIMORE_RAVENS_PATHNAME,
  logo: ravensLogo
}

const BUFFALO_BILLS_TEAM: MenuItem = {
  label: BUFFALO_BILLS_LABEL,
  link: BUFFALO_BILLS_PATHNAME,
  logo: billsLogo
}

const CAROLINA_PANTHERS_TEAM: MenuItem = {
  label: CAROLINA_PANTHERS_LABEL,
  link: CAROLINA_PANTHERS_PATHNAME,
  logo: panthersLogo
}

const CHICAGO_BEARS_TEAM: MenuItem = {
  label: CHICAGO_BEARS_LABEL,
  link: CHICAGO_BEARS_PATHNAME,
  logo: bearsLogo
}

const CINCINNATI_BENGALS_TEAM: MenuItem = {
  label: CINCINNATI_BENGALS_LABEL,
  link: CINCINNATI_BENGALS_PATHNAME,
  logo: bengalsLogo
}

const CLEVELAND_BROWNS_TEAM: MenuItem = {
  label: CLEVELAND_BROWNS_LABEL,
  link: CLEVELAND_BROWNS_PATHNAME,
  logo: brownsLogo
}

const DALLAS_COWBOYS_TEAM: MenuItem = {
  label: DALLAS_COWBOYS_LABEL,
  link: DALLAS_COWBOYS_PATHNAME,
  logo: cowboysLogo
}

const DENVER_BRONCOS_TEAM: MenuItem = {
  label: DENVER_BRONCOS_LABEL,
  link: DENVER_BRONCOS_PATHNAME,
  logo: broncosLogo
}

const DETROIT_LIONS_TEAM: MenuItem = {
  label: DETROIT_LIONS_LABEL,
  link: DETROIT_LIONS_PATHNAME,
  logo: lionsLogo
}

const GREEN_BAY_PACKERS_TEAM: MenuItem = {
  label: GREEN_BAY_PACKERS_LABEL,
  link: GREEN_BAY_PACKERS_PATHNAME,
  logo: packersLogo
}

const HOUSTON_TEXANS_TEAM: MenuItem = {
  label: HOUSTON_TEXANS_LABEL,
  link: HOUSTON_TEXANS_PATHNAME,
  logo: texansLogo
}

const INDIANAPOLIS_COLTS_TEAM: MenuItem = {
  label: INDIANAPOLIS_COLTS_LABEL,
  link: INDIANAPOLIS_COLTS_PATHNAME,
  logo: coltsLogo
}

const JACKSONVILLE_JAGUARS_TEAM: MenuItem = {
  label: JACKSONVILLE_JAGUARS_LABEL,
  link: JACKSONVILLE_JAGUARS_PATHNAME,
  logo: jaguarsLogo
}

const KANSAS_CITY_CHIEFS_TEAM: MenuItem = {
  label: KANSAS_CITY_CHIEFS_LABEL,
  link: KANSAS_CITY_CHIEFS_PATHNAME,
  logo: chiefsLogo
}

const LAS_VEGAS_RAIDERS_TEAM: MenuItem = {
  label: LAS_VEGAS_RAIDERS_LABEL,
  link: LAS_VEGAS_RAIDERS_PATHNAME,
  logo: raidersLogo
}

const LOS_ANGELES_CHARGERS_TEAM: MenuItem = {
  label: LOS_ANGELES_CHARGERS_LABEL,
  link: LOS_ANGELES_CHARGERS_PATHNAME,
  logo: chargersLogo
}

const LOS_ANGELES_RAM_TEAM: MenuItem = {
  label: LOS_ANGELES_RAM_LABEL,
  link: LOS_ANGELES_RAM_PATHNAME,
  logo: ramsLogo
}

const MIAMI_DOLPHINS_TEAM: MenuItem = {
  label: MIAMI_DOLPHINS_LABEL,
  link: MIAMI_DOLPHINS_PATHNAME,
  logo: dolphinsLogo
}

const MINNESOTA_VIKINGS_TEAM: MenuItem = {
  label: MINNESOTA_VIKINGS_LABEL,
  link: MINNESOTA_VIKINGS_PATHNAME,
  logo: vikingsLogo
}

const NEW_ENGLAND_PATRIOTS_TEAM: MenuItem = {
  label: NEW_ENGLAND_PATRIOTS_LABEL,
  link: NEW_ENGLAND_PATRIOTS_PATHNAME,
  logo: patriotsLogo
}

const NEW_ORLEANS_SAINTS_TEAM: MenuItem = {
  label: NEW_ORLEANS_SAINTS_LABEL,
  link: NEW_ORLEANS_SAINTS_PATHNAME,
  logo: saintsLogo
}

const NEW_YORK_GIANTS_TEAM: MenuItem = {
  label: NEW_YORK_GIANTS_LABEL,
  link: NEW_YORK_GIANTS_PATHNAME,
  logo: giantsLogo
}

const NEW_YORK_JETS_TEAM: MenuItem = {
  label: NEW_YORK_JETS_LABEL,
  link: NEW_YORK_JETS_PATHNAME,
  logo: jetsLogo
}

const PHILADELPHIA_EAGLES_TEAM: MenuItem = {
  label: PHILADELPHIA_EAGLES_LABEL,
  link: PHILADELPHIA_EAGLES_PATHNAME,
  logo: eaglesLogo
}

const PITTSBURGH_STEELERS_TEAM: MenuItem = {
  label: PITTSBURGH_STEELERS_LABEL,
  link: PITTSBURGH_STEELERS_PATHNAME,
  logo: steelersLogo
}

const SAN_FRANCISCO_49ERS_TEAM: MenuItem = {
  label: SAN_FRANCISCO_49ERS_LABEL,
  link: SAN_FRANCISCO_49ERS_PATHNAME,
  logo: ersLogo
}

const SEATTLE_SEAHAWKS_TEAM: MenuItem = {
  label: SEATTLE_SEAHAWKS_LABEL,
  link: SEATTLE_SEAHAWKS_PATHNAME,
  logo: seahawksLogo
}

const TAMPA_BAY_BUCCANEERS_TEAM: MenuItem = {
  label: TAMPA_BAY_BUCCANEERS_LABEL,
  link: TAMPA_BAY_BUCCANEERS_PATHNAME,
  logo: buccaneersLogo
}

const TENNESSEE_TITANS_TEAM: MenuItem = {
  label: TENNESSEE_TITANS_LABEL,
  link: TENNESSEE_TITANS_PATHNAME,
  logo: titansLogo
}

const WASHINGTON_COMMANDERS_TEAM: MenuItem = {
  label: WASHINGTON_COMMANDERS_LABEL,
  link: WASHINGTON_COMMANDERS_PATHNAME,
  logo: commandersLogo
}

export const ABOUT_GAME_SUBMENU: MenuItem[] = [GAME_HISTORY, GAME_RULES]
export const NFL_SUBMENU: MenuItem[] = [NFL_HISTORY, LEAGUE_STRUCTURE, SEASON_STRUCTURE, DRAFT]
export const SUPERBOWL_SUBMENU: MenuItem[] = [SUPERBOWL_WHAT_IS, SUPERBOWL_CHAMPIONS]
export const TEAMS_SUBMENU: MenuItem[] = [
  ARIZONA_CARDINALS_TEAM,
  ATLANTA_FALCONS_TEAM,
  BALTIMORE_RAVENS_TEAM,
  BUFFALO_BILLS_TEAM,
  CAROLINA_PANTHERS_TEAM,
  CHICAGO_BEARS_TEAM,
  CINCINNATI_BENGALS_TEAM,
  CLEVELAND_BROWNS_TEAM,
  DALLAS_COWBOYS_TEAM,
  DENVER_BRONCOS_TEAM,
  DETROIT_LIONS_TEAM,
  GREEN_BAY_PACKERS_TEAM,
  HOUSTON_TEXANS_TEAM,
  INDIANAPOLIS_COLTS_TEAM,
  JACKSONVILLE_JAGUARS_TEAM,
  KANSAS_CITY_CHIEFS_TEAM,
  LAS_VEGAS_RAIDERS_TEAM,
  LOS_ANGELES_CHARGERS_TEAM,
  LOS_ANGELES_RAM_TEAM,
  MIAMI_DOLPHINS_TEAM,
  MINNESOTA_VIKINGS_TEAM,
  NEW_ENGLAND_PATRIOTS_TEAM,
  NEW_ORLEANS_SAINTS_TEAM,
  NEW_YORK_GIANTS_TEAM,
  NEW_YORK_JETS_TEAM,
  PHILADELPHIA_EAGLES_TEAM,
  PITTSBURGH_STEELERS_TEAM,
  SAN_FRANCISCO_49ERS_TEAM,
  SEATTLE_SEAHAWKS_TEAM,
  TAMPA_BAY_BUCCANEERS_TEAM,
  TENNESSEE_TITANS_TEAM,
  WASHINGTON_COMMANDERS_TEAM
]
